kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: localhost:5000/hello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always